### ISSUE TITLE
Question: implementing `align` directive for the assembler.

### ISSUE THREAD

**Issue by ghost** [raxod502/kalyn#21]
Hey, thanks for making such an interesting compiler. I'm looking into the source code for the assembler and rewriting it in Racket to understand it better. I'm wondering how one would implement the align directive for the assembler to output padded data in the text section, my naive solution below (as a pattern match in `compileInstr`) loops indefinitely.

`      [(Align n) (make-bytes (- (round-up n pc) pc) 0)]`

Loop:
```
pc: 0
pc: 3161
pc: 3168
pc: 3161
```

**Comment by raxod502** [comment]
Sorry, you might have to fill me in on a bit more context. What lines in the Kalyn source are you trying to translate and what do you have so far?

**Comment by ghost** [comment]
I'm trying to add a new feature to enable outputting aligned binary data (like the NASM align directive allows you to), I've defined a new pseudo-instruction `ALIGN Int` and am trying to add it to the main function of the assembler. In the Haskell implementation I can reproduce it as such:

`compileInstr :: Map.Map Label Word32 -> Word32 -> PhysicalInstruction -> B.ByteString`
```
        ALIGN n   -> B.concat $ replicate (roundUp n ip - ip) $ B.pack [0]
          where ip = fromIntegral pc
```

```
*Assembler> let a = OP MOV $ IR 10 RAX
*Assembler> let b = UN PUSH $ R RDI
*Assembler> let c = RET
*Assembler> assemble $ Program (function "f" [a, b, c, ALIGN 8, RET]) [] []
=> ("... 
```
So the `fixedPoint` function hangs the whole assembler.

**Comment by ghost** [comment]
Also, to add, if the `pc` is already aligned properly (divisible by the alignment) then all is as expected.
```
assemble $ Program (function "f" [ALIGN 8, a]) [] []
=> ("H\199\192\n\NUL\NUL\NUL","",fromList [("f",0)],fromList [])
```

**Comment by raxod502** [comment]
Got it---so, if you're falling into an infinite loop when computing the fixed point, that typically means the length of your program is changing every time you run, or something like that. You probably want to modify `fixedPoint` to print out the program after each iteration, for a minimal example. You'll probably see something like an ever-expanding gulf of alignment space at your new pseudoinstruction, if there's an off-by-one error in the rounding calculation or something like that.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/radian-software/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
